![imagen](./img/ejercicios.png)

In [44]:
### IMPORTACIONES LIBRERÍAS ###
import numpy as np


## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [253]:
my_array = np.arange(10)
ej_1 = my_array.copy()
ej_1 = np.where(ej_1 % 2 != 0)[0]
print(ej_1[::-1])

[9 7 5 3 1]


In [68]:
###TODO: ¿Por qué where me devuelve una tupla?
# my_array = np.arange(10)
# print(my_array)
# print(type(my_array))
# ej_1=my_array.copy()
# np.where(my_array % 2 != 0,ej_1,ej_1)
# print(type(ej_1))
# ej_1a = ej_1[::-1]
# ej_1
my_array = np.arange(10)
print(my_array[10::-2])


[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [75]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [82]:
print(my_array[2:-11:-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [127]:
ej_4 = np.arange(1,21).reshape(4,5)
print("Matriz original:\n",ej_4)
ej_4inv = np.flip(ej_4)
print("Matriz invertida:\n",ej_4inv)

Matriz original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Matriz invertida:
 [[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [133]:
ej_5 = ej_4.copy()
ej_5fil = ([True,True,False,False])
print(ej_5[ej_5fil, 0:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [154]:
ej_6 = ej_4.copy()
ej_6_bool = ej_6 % 2 != 0
ej_6a = ej_6[ej_6_bool]
ej_6b = ej_6a.reshape(2,-1)
print(ej_6b[:,:3])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [153]:
ej_7 = ej_4.copy()
print(ej_7[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [164]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
ej_8bool = x =="Loro"
ej_8a = x.copy()
print("1.-:",ej_8a[ej_8bool])
ej_8b = x.copy()
ej_8b = ej_8b[np.ix_([0,3])]
print("2.-:",ej_8b)



1.-: ['Loro' 'Loro']
2.-: ['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [169]:
ej_9 = np.arange(20)
ej_9.reshape((2,2,5))


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [176]:
ej_10 = np.full(10,0)
print("Peso:",ej_10.nbytes)
ej_10b = ej_10.copy()
ej_10b[4] = 1
print("Array con 1:",ej_10b)



Peso: 80
Array con 1: [0 0 0 0 1 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [181]:
ej_11 = np.flip(np.arange(10,50))
print(ej_11)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [246]:
ej_12 = np.array([1,2,0,0,4,0])
ej_12 = np.nonzero(ej_12)[0]
print(ej_12)

def ind_nonzero(vector):
    nz = np.nonzero(vector)[0]
    return print(nz)

ind_nonzero(np.array([3,5,0,0,0,0,9]))


[0 1 4]
[0 1 6]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [191]:
ej_13 = np.random.randint(0,1000,(10,10))
print(ej_13)
print("Mínimo:",ej_13.min())
print("Máximo:",ej_13.max())

[[420 449 900 878 787 800 137 813 390 962]
 [265 756 118 739 858 648 923 161   5 735]
 [191 349 350  90 297  70 235 504 305 412]
 [ 20 938 535 339 479 216 261 532 298 904]
 [618 141 839  99 840 772 259  19 430 437]
 [268 816 632  86 770 740 145 833 586 765]
 [283 435 598 822 506 865 696  19 688 910]
 [247 333 461 399  21 733 402 924 137 212]
 [462 322 148 846 125 521 639 496 855 654]
 [399 187 830 661 688 402 815 345 193 740]]
Mínimo: 5
Máximo: 962


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [193]:
ej_14 = np.random.randint(0,100,30)
print(ej_14)
print("Media:",ej_14.mean())

[73 99 47 98 59 58 94 86 60 26 18 94 24  5 86 37 76 40 41 49 52 11 21 30
 28 56 46 26 85 96]
Media: 54.03333333333333


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [200]:
ej_15 = np.full((10,10),1)
ej_15[1:9,1:9] = 0
print(ej_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [207]:
ej_16 = np.array(([0,1]*4+[1,0]*4)*4).reshape(8,8)
print(ej_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [254]:
ej_17 = np.array(([0,1],[1,0]))
ej_17 = np.tile(ej_17,(4,4))
print(ej_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [258]:
ej_18 = np.random.randint(20,50,(5,5))
print("Matriz original:\n",ej_18)
print("Media de la matriz:",ej_18.mean())
ej_18 = (ej_18-ej_18.mean())/ej_18.std()
print("Resultado:\n",ej_18.round(2))


Matriz original:
 [[43 32 32 48 23]
 [23 36 35 21 43]
 [29 36 41 43 40]
 [29 37 25 33 27]
 [28 32 21 22 44]]
Media de la matriz: 32.92
Resultado:
 [[ 1.27 -0.12 -0.12  1.91 -1.25]
 [-1.25  0.39  0.26 -1.51  1.27]
 [-0.5   0.39  1.02  1.27  0.89]
 [-0.5   0.52 -1.    0.01 -0.75]
 [-0.62 -0.12 -1.51 -1.38  1.4 ]]
Media: -2.042810365310288e-16


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [240]:
ej_19 = np.arange(11)
print("1.-",ej_19)
ej_19b = ej_19.copy()
ej_19b [(ej_19b >= 3) & (ej_19b <= 8)] = -1
print("2.-",ej_19b)
ej_19c = ej_19b.copy()
for i,x in enumerate(ej_19c):
    if i >= 3 or i <=8:
        ej_19c[i] = abs(x)
print("3.-",ej_19c)


1.- [ 0  1  2  3  4  5  6  7  8  9 10]
2.- [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
3.- [ 0  1  2  1  1  1  1  1  1  9 10]
